In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.merge(credits,on='title').shape

(4809, 23)

In [7]:
movies=movies.merge(credits,on='title')

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies= movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
def convert(text):
    L=[]
    for i in ast.literal_eval(text):
        L.append(i['name'])
        return L

In [18]:
movies['genres'].apply(convert)

0            [Action]
1         [Adventure]
2            [Action]
3            [Action]
4            [Action]
            ...
4804         [Action]
4805         [Comedy]
4806         [Comedy]
4807             None
4808    [Documentary]
Name: genres, Length: 4806, dtype: object

In [19]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [20]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [21]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
import ast

In [23]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [24]:
movies.dropna(inplace=True)

In [25]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [27]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [29]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [30]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [32]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [33]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [34]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [35]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [36]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [37]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [38]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [39]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [40]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [41]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [42]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
new_df=movies[['movie_id','title','tags']]

In [44]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [45]:
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [46]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [47]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Hp\AppData\Local\Temp\ipykernel_17852\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [48]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [49]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [50]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\Hp\AppData\Local\Temp\ipykernel_17852\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [51]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [52]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [55]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [56]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [57]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2025.7.34)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [58]:
import nltk

In [59]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [60]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))   # store the stemmed word
    return " ".join(y)         # return after the loop

In [61]:
ps.stem('dancing')

'danc'

In [62]:
text = "running runner runs easily"
print(stem(text))

run runner run easili

In [63]:
print(stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'))

in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron

In [64]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Hp\AppData\Local\Temp\ipykernel_17852\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [65]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [66]:
 from sklearn.metrics.pairwise import cosine_similarity

In [67]:
similarity = cosine_similarity(vectors)

In [68]:
similarity[0]

array([1.        , 0.08858079, 0.05905386, ..., 0.02478408, 0.02599376,
       0.        ], shape=(4806,))

In [69]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    recommendations=[new_df.iloc[i[0]].title for i in movie_list]
    return recommendations

In [70]:
new_df[new_df['title']=='Batman Begins'].index[0]

np.int64(119)

In [71]:
sorted(similarity[0],reverse=True)

[np.float64(0.9999999999999998),
 np.float64(0.2537477434955704),
 np.float64(0.25112360116696136),
 np.float64(0.2442250043490654),
 np.float64(0.24260844762468367),
 np.float64(0.24165612634006073),
 np.float64(0.2372894989381248),
 np.float64(0.2372894989381248),
 np.float64(0.23692415692169538),
 np.float64(0.23394386020951635),
 np.float64(0.2324952774876386),
 np.float64(0.22305671869347438),
 np.float64(0.21919864974047634),
 np.float64(0.21775177815467112),
 np.float64(0.21582051197002577),
 np.float64(0.2152488010002526),
 np.float64(0.2113701265354594),
 np.float64(0.21059925059706258),
 np.float64(0.21049133398705727),
 np.float64(0.21029989116983447),
 np.float64(0.21029989116983447),
 np.float64(0.2101050788156825),
 np.float64(0.2071841649822589),
 np.float64(0.20668850837512243),
 np.float64(0.2056773510573183),
 np.float64(0.20567735105731827),
 np.float64(0.20032733246124987),
 np.float64(0.1973593560521103),
 np.float64(0.19727878476642874),
 np.float64(0.19374606457303215),
 np.float64(0.1934477640657483),
 np.float64(0.1926263261127128),
 np.float64(0.18983159915049982),
 np.float64(0.1898315991504998),
 np.float64(0.1898315991504998),
 np.float64(0.18857857160117855),
 np.float64(0.18790823039834775),
 np.float64(0.18668326147193276),
 np.float64(0.18641092980036),
 np.float64(0.18494886071852695),
 np.float64(0.18427434427242972),
 np.float64(0.18380365552345193),
 np.float64(0.18380365552345193),
 np.float64(0.1823843010350213),
 np.float64(0.1823843010350213),
 np.float64(0.18195633571851272),
 np.float64(0.18009006755629928),
 np.float64(0.17972365808708385),
 np.float64(0.17972365808708385),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.1771615786072478),
 np.float64(0.17684493567566834),
 np.float64(0.1752499093081954),
 np.float64(0.17170914210964275),
 np.float64(0.17155007848855516),
 np.float64(0.17139779254776524),
 np.float64(0.17139779254776524),
 np.float64(0.1696751579473019),
 np.float64(0.16916516233038026),
 np.float64(0.16702953813186466),
 np.float64(0.16673100431301852),
 np.float64(0.16673100431301852),
 np.float64(0.16569860426698665),
 np.float64(0.1643989873053573),
 np.float64(0.1643989873053573),
 np.float64(0.1643989873053573),
 np.float64(0.1643989873053573),
 np.float64(0.16120647005479025),
 np.float64(0.16120647005479025),
 np.float64(0.16120647005479025),
 np.float64(0.1600142241187995),
 np.float64(0.15958626340564364),
 np.float64(0.15819299929208316),
 np.float64(0.15794943794779692),
 np.float64(0.15794943794779692),
 np.float64(0.1559625734730109),
 np.float64(0.1553424415003),
 np.float64(0.15404884978892902),
 np.float64(0.1526406277181659),
 np.float64(0.1522038868295523),
 np.float64(0.15110651212172094),
 np.float64(0.15007505629691606),
 np.float64(0.15007505629691606),
 np.float64(0.1487044791289829),
 np.float64(0.1487044791289829),
 np.float64(0.14763464883937316),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876154),
 np.float64(0.14704292441876154),
 np.float64(0.1461508458653816),
 np.float64(0.1454358496691159),
 np.float64(0.1453095484297741),
 np.float64(0.1453095484297741),
 np.float64(0.14349920066683505),
 np.float64(0.14349920066683505),
 np.float64(0.14349920066683505),
 np.float64(0.14237369936287486),
 np.float64(0.14165281524036175),
 np.float64(0.14097096860865022),
 np.float64(0.14097096860865022),
 np.float64(0.14097096860865022),
 np.float64(0.14097096860865022),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.13949716649258312),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1371182340382122),
 np.float64(0.13699915608779772),
 np.float64(0.13678822577626598),
 np.float64(0.13678822577626598),
 np.float64(0.13678822577626598),
 np.float64(0.13678822577626595),
 np.float64(0.13513513513513514),
 np.float64(0.13513513513513514),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.13377695860286035),
 np.float64(0.13334518676566626),
 np.float64(0.13334518676566626),
 np.float64(0.13334518676566626),
 np.float64(0.13334518676566626),
 np.float64(0.13200500012082497),
 np.float64(0.13181243254912406),
 np.float64(0.1316245316231641),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12951986753290365),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1283740414907742),
 np.float64(0.1283740414907742),
 np.float64(0.12734290799340264),
 np.float64(0.12683657235796025),
 np.float64(0.12683657235796025),
 np.float64(0.12683657235796025),
 np.float64(0.12655439943366653),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.1252721535988985),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12392039927415242),
 np.float64(0.12392039927415242),
 np.float64(0.12392039927415242),
 np.float64(0.12392039927415242),
 np.float64(0.12392039927415242),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12253577034896797),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.12119654139092992),
 np.float64(0.12119654139092992),
 np.float64(0.1211965413909299),
 np.float64(0.1211965413909299),
 np.float64(0.12050719759100866),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.11990028442779209),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11874787399915188),
 np.float64(0.11810771907149853),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.1162476387438193),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11624763874381927),
 np.float64(0.11510231387903269),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.1139901881468883),
 np.float64(0.11389895949029986),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11185934253567072),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11083777463036817),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10887588907733556),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10793322294408637),
 np.float64(0.1076244005001263),
 np.float64(0.1076244005001263),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10524566699352861),
 np.float64(0.10524566699352861),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10356162766686666),
 np.float64(0.10283867552865915),
 np.float64(0.10283867552865915),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.1017387650221051),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09755285137982107),
 np.float64(0.09695723311274393),
 np.float64(0.09687303228651607),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09592022754223367),
 np.float64(0.09592022754223367),
 np.float64(0.09592022754223367),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.09428928580058928),
 np.float64(0.09394227846020416),
 np.float64(0.09367501681349609),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09299811099505542),
 np.float64(0.09299811099505542),
 np.float64(0.09299811099505542),
 np.float64(0.09248165577087424),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09158437663089954),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09133277072519848),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09077415526644964),
 np.float64(0.09032775043542898),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.0876249546540977),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08710071126186844),
 np.float64(0.08710071126186844),
 np.float64(0.0863465783552691),
 np.float64(0.0863465783552691),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08561170049453902),
 np.float64(0.08561170049453902),
 np.float64(0.08561170049453902),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482288),
 np.float64(0.08351476906593233),
 np.float64(0.08351476906593233),
 np.float64(0.08351476906593232),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08156473902861858),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.0803381317273391),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07802030664724674),
 np.float64(0.07798128673650545),
 np.float64(0.07798128673650545),
 np.float64(0.07798128673650545),
 np.float64(0.07798128673650545),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07749842582921286),
 np.float64(0.07702442489446452),
 np.float64(0.07702442489446452),
 np.float64(0.07702442489446452),
 np.float64(0.07702442489446452),
 np.float64(0.07702442489446452),

In [72]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, np.float64(0.2537477434955704)),
 (1192, np.float64(0.25112360116696136)),
 (260, np.float64(0.2442250043490654)),
 (1214, np.float64(0.24260844762468367)),
 (507, np.float64(0.24165612634006073))]

In [73]:
recommend('Avatar')

['Titan A.E.',
 'Small Soldiers',
 "Ender's Game",
 'Aliens vs Predator: Requiem',
 'Independence Day']

In [74]:
new_df.iloc[1214].title

'Aliens vs Predator: Requiem'

In [75]:
import pickle

In [76]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [77]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4806,), dtype=object)

In [78]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [78]:
pickle.dump(similarity,open('similarity.pkl','wb'))